version: '3'
services:
  backend:
    build: ./social-stories-backend/
    ports:
      - 9000:9000
    expose: 
      - 9000
    links:
    - elasticsearch
  frontend:
    build: ./social-stories-frontend/
    ports:
      - 3000:3000
    links:
      - backend
  elasticsearch:
    image: elasticsearch:7.4.1
    ports:
      - 9200:9200
      - 9300:9300
    expose: 
      - 9200
      - 9300
    environment: 
      - "discovery.type=single-node"

